name: "Front-end developer. Yaroslav Baronin"
paginate: 5
url: "https://baronin.github.io/"
github-url: "https://github.com/baronin/baronin.github.io"
base-url: ""
github-default-branch: "/edit/master/"

sass:
  style: compressed

timezone: Europe/Kiev

defaults:
  - scope:
      path: ""
    values:
      author: "Yaroslav Baronin"
      layout: post
      lang: en
      base-url: "/"
  - scope:
      path: ua
    values:
      lang: ua
      base-url: "/ua/"

plugins: [
  "jekyll-paginate",
  "github-pages",
]

# For travis
exclude: [vendor]

# Value to use into url per language
langs-value:
  en: ""
  ua: ua

# Translation
t:
  home:
    en: "Home"
    ua: "Головна"
  blog:
    en: "Blog"
    ua: "Блог"
  project:
    en: "Projects"
    ua: "Проекти"
  about-me:
    en: "About me"
    ua: "Про мене"
  contact:
    en: "Contact"
    ua: "Контакти"
  subtitle:
    en: "My very own part of the Internet"
    ua: "Моя власна частина Інтернету"
  footer-article:
    en: "Found a mistake, or just want to add your words to this post ?"
    ua: "Ви знайшли помилку чи просто хочете додати свої слова до цієї публікації?"
  fork:
    en: "Fork it on github"
    ua: "Викладіть його на github"
  desc:
    en: "Front-end developer. Yaroslav Baronin"
    ua: "Веб-мастер. Ярослав Баронін"
  download:
    en: "Download CV"
    ua: "Завантажити резюме"
  title-project:
    en: "These are not all my projects. Big projects were the NDA"
    ua: "Це не всі мої проекти. Великі проекти були в рамках NDA"
  about-title:
    en: "Web development, UI and UX"
    ua: "Web development, UI and UX"
  about-subtitle:
    en: "Website development for your business"
    ua: "Розробка сайтів для вашого бізнесу"
  about-desc:
    en: "I sincerely love web development and web design, am actively learning new standards, and in my free time I share my experience with people who want to take on a new profession."
    ua: "Я щиро люблю веб-розробку та веб-дизайн, активно вивчаю нові стандарти, а у вільний час ділюся своїм досвідом з людьми які хочуть оволодіти новою професією."

